# docker-compose.yml
version: "3"
services:
  backend:
    build:
      context: ./backend  # Ensure this points to the correct backend folder
      dockerfile: Dockerfile  # Make sure Dockerfile is in the backend folder
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/social-food-delivery-system
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend  # Ensure this points to the correct frontend folder
      dockerfile: Dockerfile  # Make sure Dockerfile is in the frontend folder
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
